# Generated by Django 3.1.4 on 2020-12-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='currency_data')),
            ],
            options={
                'verbose_name': 'Currrency File',
                'verbose_name_plural': 'Currency File',
            },
        ),
    ]
